export const lockedGoldAbi = [
  {
    type: "function",
    name: "getTotalLockedGold",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAccountTotalLockedGold",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAccountNonvotingLockedGold",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAccountTotalGovernanceVotingPower",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAccountTotalDelegatedFraction",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingWithdrawals",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "values", type: "uint256[]" },
      { name: "timestamps", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unlockingPeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDelegateesOfDelegator",
    inputs: [{ name: "delegator", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDelegatorDelegateeInfo",
    inputs: [
      { name: "delegator", type: "address" },
      { name: "delegatee", type: "address" },
    ],
    outputs: [
      { name: "fraction", type: "uint256" },
      { name: "currentAmount", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lock",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "unlock",
    inputs: [{ name: "value", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "relock",
    inputs: [
      { name: "index", type: "uint256" },
      { name: "value", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "delegateGovernanceVotes",
    inputs: [
      { name: "delegatee", type: "address" },
      { name: "delegateFraction", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeDelegatedGovernanceVotes",
    inputs: [
      { name: "delegatee", type: "address" },
      { name: "revokeFraction", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
