/**
 * Generated by scripts/generate-mcp-analytics-map.mjs — do not edit by hand.
 * Catalog-derived rules for extracting wallet addresses from SDK read call args.
 */
export type WalletExtractRule = {
  positional?: number;
  objectKeys?: readonly string[];
};

export const WALLET_EXTRACT_BY_SDK_METHOD: Readonly<
  Record<string, WalletExtractRule>
> = {
  "account.getAccount": { positional: 0, objectKeys: ["address"] },
  "carbon.getActivity": { objectKeys: ["address","wallet_address"] },
  "carbon.getStrategies": { positional: 0, objectKeys: ["address","wallet_address"] },
  "contract.estimateGas": { objectKeys: ["fromAddress"] },
  "gooddollar.getUbiClaimEligibility": { positional: 0, objectKeys: ["address"] },
  "gooddollar.getWhitelistingInfo": { positional: 0, objectKeys: ["address"] },
  "nft.getNftBalance": { objectKeys: ["address"] },
  "self.verifySelfAgent": { objectKeys: ["address"] },
  "staking.getActivatableStakes": { positional: 0, objectKeys: ["address"] },
  "staking.getStakingBalances": { positional: 0, objectKeys: ["address"] },
  "token.getBalances": { objectKeys: ["address"] },
  "token.getStablecoinBalances": { positional: 0, objectKeys: ["address"] },
  "token.getTokenBalance": { positional: 1, objectKeys: ["address"] },
  "transaction.estimateSend": { positional: 1 },
  "transaction.estimateTransaction": { objectKeys: ["from"] },
} as const;
